### ISSUE TITLE
Rate limits

### ISSUE THREAD

**Issue by satom99** [satom99/litcord#9]
Proper [rate limits](https://discordapp.com/developers/docs/topics/rate-limits) support required, must be [#108](https://github.com/hammerandchisel/discord-api-docs/issues/108) compliant.

**Comment by roastchicken** [comment]
Is litcord not already hammerandchisel/discord-api-docs#108 compliant? It's listed as "known to do queuing/throttling properly" in the issue, and you commented saying:

> _litcord_'s indev branch [now supports](https://github.com/satom99/litcord/commit/ddaaa868c4b84c822c179b2d6929749e0ee5f772) the new rate limits.

**Comment by satom99** [comment]
That was before new documentation came out, so a rework is required.

**Comment by roastchicken** [comment]
Ah, I see. I'll take a look at the code and see what I can do over the weekend.

**Comment by roastchicken** [comment]
Sorry for not coming back to this sooner. I took a look at the code, specifically [client/rest.lua](https://github.com/satom99/litcord/blob/indev/litcord/client/rest.lua) but I'm still not sure what needs changing. It looks to me like you're doing everything as the docs says you should: check the header for the rate limits and limit accordingly.

edit: While writing this comment I saw that the limits table had keys for request.method, and after finding an example of how rest:request is called I now see that you're organizing the limits by method. I assume this is the required change, as the docs say that the limits are per path and not per method now. Let me know if this is not the case, otherwise I will try to work on this sometime during the week and hopefully make a pull request by this weekend.

**Comment by satom99** [comment]
More specifically, limits work by [major parameters](https://github.com/hammerandchisel/discord-api-docs/blame/master/docs/topics/Rate_Limits.md#L5), which are not implemented yet, together with routes.

EDIT: Looks like rest/_LuaSec_ does not format _GET_ requests properly - another thing to implement.
